Ruby translation of GnuPG-checking Git hook
saab-simc-admin/workflow-tools pull request #4
Opened 2017-01-10 07:47 UTC by creideiki

The Git server-side hook checking GnuPG signatures is currently (see https://github.com/saab-simc-admin/scripts) written in Bash, which makes me nervous. This is a straight translation into Ruby, using Rugged and GPGME.

This needs a lot more testing before it can be accepted.

2017-01-11 10:08 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +      puts e
Is it really safe to continue if there is an exception?

2017-01-11 10:17 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +          puts "*** Tag #{ref} already exists."
The doc at top says that the config options for this is `hooks.allowmodifytag`

2017-01-11 10:25 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +              puts "*** Rejecting tag #{ref} due to lack of a valid GPG signature."
Harmonize the signature rejection handling for tags and commits.

2017-01-11 15:27 UTC, notCalle requested changes
In general very difficult to read, because there is a `.each do ... end` spanning > 100 lines that does almost everything in deeply nested logic structures.

The overall design is insecure because it accepts by default. The default should be to reject, unless the specific circumstances where a push is allowed has been verified.

Probably needs a `Gemfile` to describe its dependencies.

2017-01-11 15:27 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +  if not repo.config['hooks.allowunsignedtags']
The top comment states that the config options for this is `hooks.allowcommitsonmaster`.

2017-01-11 15:27 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +          not parents.include?(rev_old)
The initial commit on `master` also needs to be pushable.

2017-01-11 15:27 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +  keys = GPGME::Key.find(keyid)
`GPGME::Key.find` does not work that way. The first arg should be `:public` to find public keys, and the needle should be in the second arg.

2017-01-11 15:27 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +  walker.push(rev_new)
When pushing a branch deletion, `rev_new` is zeroes, which cannot be pushed.

2017-01-11 15:27 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +      commit_type = :delete
I don't think ref deletions can appear in the actual commit graph.

2017-01-11 15:27 UTC, notCalle commented on git-hooks/enforce-workflow.rb
> +    if commit_count == 0
This condition is always false unless moved outside the `walker.each` block.

2017-02-07 14:06 UTC, creideiki commented
Pushed 9045ea1 which I think should solve all actual bugs before I start restructuring the logic. However, the call to `Rugged::Commit.extract_signature` likes to corrupt the last couple of bytes of the plaintext on my system, so it makes spurious claims of signatures being bad.

2017-02-09 12:25 UTC, creideiki commented
Signature validation fails due to a bug in libgit2: libgit2/libgit2#4118

2017-03-27 14:52 UTC, creideiki commented
I no longer see random signature validation failures as of Rugged 0.26.0b5.

2017-04-05 11:06 UTC, creideiki commented
This should be ready for another look now.

2017-04-05 12:30 UTC, notCalle commented
Pushing the initial commit to an empty repo still fails.
```
remote: *** Accepting creation of master branch.
To /Users/calle/Workspace/signed-only.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '/Users/calle/Workspace/signed-only.git'
```

2017-04-05 12:33 UTC, creideiki commented
I have no idea what you are talking about. It's always worked wonderfully, with no bugs whatsoever.

2017-04-05 16:18 UTC, notCalle commented
Using `git` >= 2.11 seems to break `pre-receive`, so that should be noted somewhere... 😞

`git` 2.11.0 and 2.12.2:

```
Counting objects: 3, done.
Writing objects: 100% (3/3), 845 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: hooks/pre-receive:126:in `push': object not found - no match for id (f5f1e8e9f4511a7c83de6eefb0b99c9b5331e03a) (Rugged::OdbError)
remote: 	from hooks/pre-receive:126:in `walk_graph'
remote: 	from hooks/pre-receive:288:in `block in <main>'
remote: 	from hooks/pre-receive:266:in `each'
remote: 	from hooks/pre-receive:266:in `<main>'
remote: *** Accepting creation of master branch.
To /Users/calle/Workspace/signed-only.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '/Users/calle/Workspace/signed-only.git'
```

`git` 2.10.1:

```
Counting objects: 3, done.
Writing objects: 100% (3/3), 845 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: *** Accepting creation of master branch.
remote: *** Good signature on commit f5f1e8e9f4511a7c83de6eefb0b99c9b5331e03a by calle@discord.bofh.se (1764CE72729D4C843AF6999A78D9BF4A13F75F59).
To /Users/calle/Workspace/signed-only.git
 * [new branch]      master -> master
```

2017-04-05 16:30 UTC, notCalle commented
Pushing a new (signed) tag fails:
```
Counting objects: 1, done.
Writing objects: 100% (1/1), 793 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: *** Tag refs/tags/with-readme already exists.
remote: *** Modifying a tag is not allowed in this repository.
To /Users/calle/Workspace/signed-only.git
 ! [remote rejected] with-readme -> with-readme (pre-receive hook declined)
error: failed to push some refs to '/Users/calle/Workspace/signed-only.git'
```

2017-04-07 09:02 UTC, notCalle commented
Pushing a new unsigned tag fails with stack trace instead of proper error message.
```
Counting objects: 1, done.
Writing objects: 100% (1/1), 181 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: /usr/local/lib/ruby/gems/2.4.0/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:447:in `verify': No data (GPGME::Error::NoData)
remote: 	from /usr/local/lib/ruby/gems/2.4.0/gems/gpgme-2.0.12/lib/gpgme/crypto.rb:312:in `block in verify'
remote: 	from /usr/local/lib/ruby/gems/2.4.0/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:79:in `new'
remote: 	from /usr/local/lib/ruby/gems/2.4.0/gems/gpgme-2.0.12/lib/gpgme/crypto.rb:311:in `verify'
remote: 	from hooks/pre-receive:237:in `allow_annotated_tag?'
remote: 	from hooks/pre-receive:308:in `block in <main>'
remote: 	from hooks/pre-receive:270:in `each'
remote: 	from hooks/pre-receive:270:in `<main>'
To /Users/calle/Workspace/signed-only.git
 ! [remote rejected] with-readme -> with-readme (pre-receive hook declined)
error: failed to push some refs to '/Users/calle/Workspace/signed-only.git'
```

2017-04-10 09:07 UTC, notCalle commented on git-hooks/enforce-workflow/enforce-workflow.rb
> +      puts "*** Rejecting tag #{ref} due to lack of a valid GPG signature."
Lies! It has a valid signature, but the signer is not authorized (see `walk_graph`). 

Also, maybe consider a DRYer approach to signature validation and reporting?

2017-04-10 14:36 UTC, notCalle approved these changes

2017-04-10 14:40 UTC, merged